### ISSUE TITLE
Route with custom location of user resource edit is not defined

### ISSUE THREAD

**Issue by iniznet** [TappNetwork/filament-authentication-log#1]
Hi there,

I got an issue where if you move the default user model into another directory it will result in the `Route [filament.admin.resources.users.edit] not defined.` error.

After digging into the package, I found that that the issue lies in the file `vendor\tapp\filament-authentication-log\src\Resources\AuthenticationLogResource.php`, particularly at line 77. The code at this line only extracts the class name without considering the model's location. Consequently, this approach generates an incorrect route.
https://github.com/TappNetwork/filament-authentication-log/blob/9a39e39a1b9c7f3b6f11d12e77ec0e3a76d555e2/src/Resources/AuthenticationLogResource.php#L72-L78

In my project, I moved both the user model and the Filament user resource to the Management directory, assigning the namespaces as follows: `App\Models\Management` and `App\Filament\Resources\Management`.

Temporary Workaround:
```php
use App\Models\Management\User;

class UserResource extends Resource
{
    protected static ?string $model = User::class;
    protected static ?string $slug = 'users'; // remove 'management' from the slug
...
```

A possible fix for this issue:
1. Take anything after Models
2. Replace the remaining slashes with a dot
3. Do the original string manipulation
```php
$authenticatable = Str::replace('\\', '.', Str::after($record->authenticatable::class, 'Models\\'));
$authenticatable = Str::plural(Str::lower($authenticatable));

return new HtmlString('<a href="'.route('filament.admin.resources.'.$authenticatable.'.edit', ['record' => $record->authenticatable_id]).'" class="inline-flex items-center justify-center text-sm font-medium hover:underline focus:outline-none focus:underline filament-tables-link text-primary-600 hover:text-primary-500 filament-tables-link-action">'.class_basename($record->authenticatable::class).'</a>');
```

**Comment by mrailton** [comment]
I'm getting the same error however I have not moved the User model out of `App\Models`. The only change I've made from stock is by moving the panel to the root of the application (ie, not in /admin). Unfortunately this is blocking using the plugin.

**Comment by andreia** [comment]
@iniznet Thank you for catching and reporting this :)
@mrailton Thank you for taking the time to work on this :)
