### ISSUE TITLE
Compatibility with Filament Shield / Spatie Permissions

### ISSUE THREAD

**Issue by acobrerosf** [TappNetwork/filament-authentication-log#12]
I have installed your package and works great, however I can't find a way to hide the section or block users that has a role with no permissions to handle that resource.

I don't have to do anything special for the sections that I build myself, I create a new resource and with the Shield plugin I can assign to a role the permissions to be able to create, view, edit, etc. that resource. Just by doing that the left menu item shows or not depending on the role, however with your plugin it seems to ignore these rules.

Is there anything else I need to do?

**Comment by acobrerosf** [comment]
Never mind, after some deeper research I found out that I had to register the policy in the AuthServiceProvider and link it to the AuthenticationLog model.

This is the first time I need to add permissions to a third party plugin on Filament so I had no idea this could happen.

Thanks for your work!

**Comment by andreia** [comment]
@acobrerosf Nice, many thanks for your feedback! :)

**Comment by pasteko** [comment]
> Never mind, after some deeper research I found out that I had to register the policy in the AuthServiceProvider and link it to the AuthenticationLog model.

Can't make it work, can you show how you did it please?

**Comment by acobrerosf** [comment]
> > Never mind, after some deeper research I found out that I had to register the policy in the AuthServiceProvider and link it to the AuthenticationLog model.
> 
> Can't make it work, can you show how you did it please?

Sure! I just modified the AuthServiceProvider as shown below:

```
<?php

namespace App\Providers;

// use Illuminate\Support\Facades\Gate;

use App\Policies\AuthenticationLogPolicy;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use Rappasoft\LaravelAuthenticationLog\Models\AuthenticationLog;

class AuthServiceProvider extends ServiceProvider
{
    /**
     * The model to policy mappings for the application.
     *
     * @var array<class-string, class-string>
     */
    protected $policies = [
        AuthenticationLog::class => AuthenticationLogPolicy::class,
    ];

    /**
     * Register any authentication / authorization services.
     */
    public function boot(): void
    {
        //
    }
}
```

Make sure to run as well:

```
php artisan shield:install
```

To force the plugin to generate the policies and permissions neeed for this new resource.

**Comment by StevyMarlino** [comment]
In laravel 11 you should do it in AppServiceProvider.php in the boot method as indicate in the laravel documentation.
```php
use App\Models\Order;
use App\Policies\OrderPolicy;
use Illuminate\Support\Facades\Gate;
 
/**
 * Bootstrap any application services.
 */
public function boot(): void
{
    Gate::policy(Order::class, OrderPolicy::class);
}
```

**Comment by brianglz** [comment]
Hola a todos.

Que sucedes si hay algo como esto en AdminPanelProvider.php

->navigationItems([
                NavigationItem::make('Analytics')->label('Analytics')
                    ->url('https://filament.pirsch.io', shouldOpenInNewTab: true)
                    ->icon('heroicon-o-presentation-chart-line')
                    ->group('Estadísticas')
                    ->sort(1),
                NavigationItem::make('Profile') 
                ->label(fn (): string => __('filament-panels::pages/auth/edit-profile.label'))
                ->url(fn () => EditProfile::getUrl())
                ->icon('heroicon-o-user-circle')
                ->group('Usuarios')
                ->isActiveWhen(fn (): bool => request()->routeIs(EditProfile::getRouteName())), 
            ])
->userMenuItems([
                MenuItem::make()
                    ->label(__('Users'))
                    ->url(fn (): string => UserResource::getUrl())
                    ->icon('heroicon-o-user'),
                MenuItem::make()
                    ->label('DRCensos')
                    ->url(fn (): string => CensoResource::getUrl())
                    ->icon('heroicon-o-rectangle-stack'),
                ])
