### ISSUE TITLE
AuthenticationLogsRelationManager  Table column Authenticatable is not sortable

### ISSUE THREAD

**Issue by zenepay** [TappNetwork/filament-authentication-log#19]
I registered this to UserResource.
When clicking the table header to sort coulumn Authenticatable , it turns to this error message:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'authenticatable' in 'order clause'
![errir](https://github.com/user-attachments/assets/025039ea-919e-4e87-871f-b67c629fc0a2)

**Comment by swilla** [comment]
This should be fixed in the latest release.
