### ISSUE TITLE
Can I override AuthenticationLogResource ?

### ISSUE THREAD

**Issue by anthoz69** [TappNetwork/filament-authentication-log#3]
I create my own AuthenticationLogResource  and extends Tapp\FilamentAuthenticationLog\Resources\AuthenticationLogResource
I need to override getEloquentQuery on resource but not work. how I can custom query AuthenticationLogResource ? Please help.

thank you.

**Comment by quasiperfect** [comment]
yes @anthoz69  you can just create a `AuthenticationLogResource.php` file in `app\Filament\Resources\AuthenticationLogResource.php`
```
namespace App\Filament\Resources;
use Tapp\FilamentAuthenticationLog\RelationManagers\AuthenticationLogsRelationManager;

class AuthenticationLogResource extends \Tapp\FilamentAuthenticationLog\Resources\AuthenticationLogResource
{
}
```

and in the config file
```
<?php

use App\Filament\Resources\AuthenticationLogResource;

return [

    'resources' => [
        //'AutenticationLogResource' => \Tapp\FilamentAuthenticationLog\Resources\AuthenticationLogResource::class,
        'AutenticationLogResource' => AuthenticationLogResource::class,
    ],

**Comment by andreia** [comment]
Hi @anthoz69 @quasiperfect 

Yeah, you can :)

Please check the answer here: https://github.com/TappNetwork/filament-authentication-log/issues/6#issuecomment-1714629724
