### ISSUE TITLE
Table Not Created

### ISSUE THREAD

**Issue by isaandreanme** [TappNetwork/filament-authentication-log#4]
Base table or view not found: 1146 Table 'db.authentication_log' doesn't exist

**Comment by mrailton** [comment]
@zimamarrois you need to make sure you follow the installation details for https://github.com/rappasoft/laravel-authentication-log as it is a dependency of this plugin

**Comment by andreia** [comment]
@zimamarrois Did you follow the installation instructions in https://github.com/rappasoft/laravel-authentication-log? This package is required and it should be installed before the plugin installation: https://github.com/TappNetwork/filament-authentication-log#installation.
  
Please let me know if it's working for you.
