### ISSUE TITLE
Navigation group

### ISSUE THREAD

**Issue by quasiperfect** [TappNetwork/filament-authentication-log#5]
Thanks for your work.

Please make navigation group configurable so i can group with other resources

**Comment by quasiperfect** [comment]
I have seen that is possible to change in the config the resource class so i tried to create a new resource that extends your class but i get the error `Route [filament.admin.resources.authentication-logs.index] not defined.` any idea what i'm doing wrong ?

**Comment by abbasmashaddy72** [comment]
Unable to change Navigation Group Name

@quasiperfect
