### ISSUE TITLE
Call to undefined method App\Models\User::authentications()

### ISSUE THREAD

**Issue by LionHackerman** [TappNetwork/filament-authentication-log#8]
When logging in or signing out I get the error "Call to undefined method App\Models\User::authentications()".

**Comment by LionHackerman** [comment]
New issue: This cache store does not support tagging.

**Comment by howdu** [comment]
Check the docs for https://rappasoft.com/docs/laravel-authentication-log/v1/start/configuration#content-setting-up-your-model

Also you can use array by editing your .env file
```
CACHE_DRIVER=array
```

**Comment by swilla** [comment]
I'm pretty sure this error is due to a version mismatch. I think v4 introduced authentications() relation:
https://github.com/rappasoft/laravel-authentication-log
